# This is a configuration file for Horus centralized controller

title = "Horus centralizer controller"

# Available options: trace, debug, info, warn, error, fatal, panic
[log]
level = "debug"

[rpc]
  [rpc.servers]
      # communicating with switch controllers via gRPC
      topoAddress = "0.0.0.0:4001"
      vcAddress = "0.0.0.0:4101"