[[vc]]
    id = 0
    spines = [0]
        [[vc.servers]]
            id = 0
            workersIDs = [0, 2, 3]
        [[vc.servers]]
            id = 1
            workersIDs = [2, 3, 4]

[[vc]]
    id = 1
    spines = [0]
        [[vc.servers]]
            id = 1
            workersIDs = [0, 1]
        [[vc.servers]]
            id = 2
            workersIDs = [0, 4]