# This is a configuration file for Horus centralized controller

title = "Horus centralizer controller"

# Available options: trace, debug, info, warn, error, fatal, panic
[log]
level = "debug"

[server]
    srvAddress = "0.0.0.0:4001"