# This is a configuration file for Horus centralized controller

title = "Horus centralizer controller"

[rpc]
  [rpc.servers]
      # communicating with switches via gRPC
      topoAddress = "0.0.0.0:4401"
      vcAddress = "0.0.0.0:3301"

