# Default topology
#                                           Spine0
#            +--------------------------------|--------------------------------+
#            |                                |                                |
#          Leaf0                            Leaf1                            Leaf2
#    +-------|-------+                +-------|-------+                +-------|-------+
#    |       |       |                |       |       |                |       |       |
# Server0 Server1 Server2          Server3 Server4 Server5          Server6 Server7 Server8
#    |       |       |                |       |       |                |       |       |
# W00-W07 W08-W15 W16-W23          W00-W07 W08-W15 W16-W23          W00-W07 W08-W15 W16-W23

# Important Notes:
# The IDs of Spines, Leaves, and Servers are *global*, starting from 0
# The IDs of workers per Leaf are local to that Leaf

[topology]
    [[topology.spines]]
        id = 0
        address = "0.0.0.0:5001"
        leaves = [0, 1, 2]

    [[topology.leaves]]
        id = 0
        index = 0
        address = "0.0.0.0:6001"
        mgmtAddress = "0.0.0.0:7001"
        servers = [0] # order matters

    [[topology.leaves]]
        id = 1
        index = 1
        address = "0.0.0.0:6002"
        mgmtAddress = "0.0.0.0:7001"
        servers = [1] # order matters

    [[topology.leaves]]
        id = 2
        index = 2
        address = "0.0.0.0:6003"
        mgmtAddress = "0.0.0.0:7001"
        servers = [2] # order matters

    [[topology.servers]]
        id = 0
        port_id = 1
        address = "00:00:00:00:00:00"
        workers_count = 8

    [[topology.servers]]
        id = 1
        port_id = 1
        address = "11:11:11:11:11:11"
        workers_count = 8

    [[topology.servers]]
        id = 2
        port_id = 1
        address = "22:22:22:22:22:22"
        workers_count = 8