# This is a configuration file for Horus centralized controller

title = "Horus centralizer controller"

[rpc]
  [rpc.servers]
      # communicating with switches via gRPC
      rpcAddress = "0.0.0.0:4401"

[spines]
# the current convention is:
# XXX
addresses = [
  "0.0.0.0:5501",
]