# This is a configuration file for Horus switch controller
title = "Horus switch controller"

# Available options: trace, debug, info, warn, error, fatal, panic
[log]
level = "debug"

# only for Tofino
[asic]
    intf = "bf_pci0"
    program = "saqr"
    device_id = 0
    pipe_id = 65535

# used by BfRt clients
[bfrt]
    address = "0.0.0.0:50052"

# used by spine and/or leaf switches
[centralized]
    srvAddress = "0.0.0.0:4001"

# specifies the leaf & spine controllers managed by this specific "switch manager"
[controllers]
    mgmtAddress = "0.0.0.0:7001"
    timeout = 1000 # in milliseconds
    # Options are: "fake" | "v1" | "v2"
    controlAPI = "fake" 
    [[controllers.spines]]
        id = 100
        pipeID = 65535
    [[controllers.leaves]]
        id = 0
        pipeID = 65535
    [[controllers.leaves]]
        id = 1
        pipeID = 65535
    [[controllers.leaves]]
        id = 2
        pipeID = 65535
    [[controllers.leaves]]
        id = 3
        pipeID = 65535
    # spines = [0]
    # leaves = [0, 1, 2]
    
