# This is a configuration file for Horus switch controller
title = "Horus switch controller"

# only for Tofino
[asic]
    intf = "bf_pci0"
    program = "orca"
    device_id = 0
    pipe_id = 65535

# used by spine and/or leaf switches
[centralized]
    topoAddress = "0.0.0.0:4001"
    vcAddress = "0.0.0.0:4101"

# used by spine and leaf switches
[bfrt]
    address = "0.0.0.0:50052"

# specifies the leaf & spine controllers managed by this specific "switch controller"
[controllers]
    mgmtAddress = "0.0.0.0:7001"
    spines = [0]
    leaves = [0, 1, 2]
    timeout = 1000 # in milliseconds