# All the available ASICs in the DC
[asics]
    [[asics.asic]]
        id = "tofino"
        program = "saqr"
        deviceId = 0
        pipeId = 65535
        ctrlAddress = "0.0.0.0:50052"
        ctrlAPI = "bfrt" # Options: "fake" | "bfrt"

[ports]
    # IMPORTNT NOTES: 
    # 1. This works by specifying common port configs, each has a unique ID.
    # Then, you define the a group of port specs with a specific port config.
    # 2. Available Options (for [[ports.config]])
    # id = "UniqueID" identifies this configuration to be used later
    # speed = "1G" | "10G" | "25G" | "40G" | "50G" | "100G"
    # fec = "NONE" | "FC" (firecode for 40G) | "RS" (Reed-Solomon for 100G)
    # an = "AUTO" | "ENABLED" | "DISABLED"
    # 3. Port Specs (used in [[ports.group]]):
    # "cage/lane", where the lane is one value of {-,0,1,2,3}
    # For example, "1/-" means ports "1/0", "1/1", "1/2" and "1/3"
    # 4. It's your responsibility to ensure that the cage/lane 
    # and speed values are consistent!
    [[ports.config]]
        id = "10G"
        speed = "10G"
        fec = "NONE"
        an = "DISABLED"
    
    [[ports.config]]
        id = "100G"
        speed = "100G"
        fec = "NONE"
        an = "AUTO"
        
    [[ports.group]]
        asic = "tofino"
        specs = ["1/-", "2/-", "3/-", 
                 "4/-", "9/-"]
        config = "10G"
    
    [[ports.group]]
        asic = "tofino"
        specs = ["19/0", "20/0", "21/0", "22/0", 
                 "23/0", "24/0", "25/0", "26/0", 
                 "27/0", "28/0", "29/0", "30/0"]
        config = "100G"

[topology]
    # Applications sending tasks and receiving their results
    [[topology.clients]]
        id = 110
        asic = "tofino"
        port = "9/0" # client <-> spine

    [[topology.spines]]
        id = 100
        address = "0.0.0.0:5001"
        leaves = [0, 1, 2, 3]
        asic = "tofino"

    [[topology.leaves]]
        # horus-specific values
        id = 0
        index = 0
        address = "0.0.0.0:6001"
        mgmtAddress = "0.0.0.0:7001"
        servers = [0] # order matters
        # switch-specific values
        asic = "tofino"
        us_port = "21/0" # from leaf->spine
        ds_port = "27/0" # from spine->leaf

    [[topology.leaves]]
        # horus-specific values
        id = 1
        index = 1
        address = "0.0.0.0:6002"
        mgmtAddress = "0.0.0.0:7001"
        servers = [1] # order matters
        # switch-specific values
        asic = "tofino"
        us_port = "22/0" # from leaf->spine
        ds_port = "28/0" # from spine->leaf
        
    [[topology.leaves]]
        # horus-specific values
        id = 2
        index = 2
        address = "0.0.0.0:6003"
        mgmtAddress = "0.0.0.0:7001"
        servers = [2] # order matters
        # switch-specific values
        asic = "tofino"
        us_port = "19/0" # from leaf->spine
        ds_port = "25/0" # from spine->leaf

    [[topology.leaves]]
        # horus-specific values
        id = 3
        index = 3
        address = "0.0.0.0:6004"
        mgmtAddress = "0.0.0.0:7001"
        servers = [3] # order matters
        # switch-specific values
        asic = "tofino"
        us_port = "23/0" # from leaf->spine
        ds_port = "29/0" # from spine->leaf

    #cs-nsl-55
    [[topology.servers]]
        id = 0
        port = "1/0" # server<->leaf
        address = "F8:F2:1E:3A:13:EC"
        workers_count = 8

    #cs-nsl-56
    [[topology.servers]]
        id = 1
        port = "1/2" # server<->leaf
        address = "F8:F2:1E:3A:13:0C"
        workers_count = 8
    
    #cs-nsl-57
    [[topology.servers]]
        id = 2
        port = "2/0" # server<->leaf
        address = "F8:F2:1E:3A:13:C4"
        workers_count = 8

    #cs-nsl-58
    [[topology.servers]]
        id = 3
        port = "2/2" # server<->leaf
        address = "F8:F2:1E:3A:07:24"
        workers_count = 8
