[[vc]]
    id = 0
    spines = [0]
        [[vc.servers]]
            id = 0
            workersIDs = [0, 2, 3]
        [[vc.servers]]
            id = 4
            workersIDs = [8, 9, 10]

[[vc]]
    id = 1
    spines = [0]
        [[vc.servers]]
            id = 1
            workersIDs = [8, 11]
        [[vc.servers]]
            id = 2
            workersIDs = [22, 23]