# This is a configuration file for Horus centralized controller

title = "Horus centralizer controller"

[rpc]
  [rpc.servers]
      # communicating with switch controllers via gRPC
      topoAddress = "0.0.0.0:4001"
      vcAddress = "0.0.0.0:4101"