# Default topology
#                                           Spine0
#            +--------------------------------|--------------------------------+
#            |                                |                                |
#          Leaf0                            Leaf1                            Leaf2
#    +-------|-------+                +-------|-------+                +-------|-------+
#    |       |       |                |       |       |                |       |       |
# Server0 Server1 Server2          Server3 Server4 Server5          Server6 Server7 Server8
#    |       |       |                |       |       |                |       |       |
# W00-W07 W08-W15 W16-W23          W00-W07 W08-W15 W16-W23          W00-W07 W08-W15 W16-W23

# Important Notes:
# The IDs of Spines, Leaves, and Servers are *global*, starting from 0
# The IDs of workers per Leaf are local to that Leaf

[topology]
    [[topology.spines]]
        id = 0
        address = "0.0.0.0:5001"
        leaves = [0, 1, 2, 3]

    [[topology.leaves]]
        id = 0
        index = 0
        address = "0.0.0.0:6001"
        port_id = 1
        mgmtAddress = "0.0.0.0:7001"
        servers = [0] # order matters

    [[topology.leaves]]
        id = 1
        index = 1
        address = "0.0.0.0:6002"
        port_id = 1
        mgmtAddress = "0.0.0.0:7001"
        servers = [1] # order matters

    [[topology.leaves]]
        id = 2
        index = 2
        address = "0.0.0.0:6003"
        mgmtAddress = "0.0.0.0:7001"
        servers = [2] # order matters

    [[topology.leaves]]
        id = 3
        index = 3
        address = "0.0.0.0:6004"
        mgmtAddress = "0.0.0.0:7001"
        servers = [3] # order matters
     
    #cs-nsl-55
    [[topology.servers]]
        id = 0
        port_id = 132
        address = "F8:F2:1E:3A:13:EC"
        workers_count = 8

    #cs-nsl-56
    [[topology.servers]]
        id = 1
        port_id = 134
        address = "F8:F2:1E:3A:13:0C"
        workers_count = 8
    
    #cs-nsl-57
    [[topology.servers]]
        id = 2
        port_id = 140
        address = "F8:F2:1E:3A:13:C4"
        workers_count = 8

    #cs-nsl-58
    [[topology.servers]]
        id = 3
        port_id = 142
        address = "F8:F2:1E:3A:07:24"
        workers_count = 8
